 # List of plugins
 set -g @plugin 'tmux-plugins/tpm'
 set -g @plugin 'tmux-plugins/tmux-sensible'
 set -g @plugin 'tmux-plugins/tmux-resurrect'
 set -g @plugin 'tmux-plugins/tmux-continuum'

 # Set default shell
 set-option -g default-shell /bin/bash
 # other settings, such as:

 # Set scrollback buffer to 10000
 set -g history-limit 10000

 # Enable mouse support (works in terminals that support it)
 set -g mouse on
 
 # Enable copy using y
 set-window-option -g mode-keys vi
 
 bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"


 # Don't rename windows automatically
 set-option -g allow-rename off

 # look good
 set -g default-terminal "screen-256color"

 # for making Neovim work good
 set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'

 # continuum settings, for auto restore
 set -g @continuum-restore 'on'
 
 set -g @resurrect-capture-pane-contents 'on'

 # Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
 run '~/.tmux/plugins/tpm/tpm'